"""Citation verification: the gate between the model and the user.

The model never gets to put text on screen as a quote. It only *claims* that a
quote exists in a given segment. For every claim this module:

1. Looks up the claimed segment by id (ids are generated by the parser, and
   the timestamp shown to the user is read from the segment, never from the
   model).
2. Normalises both the quote and the segment text: case, whitespace and
   punctuation only. No stemming, no fuzzy matching, no synonyms.
3. Requires the normalised quote to be a contiguous substring of the
   normalised segment text. Quotes spliced with an ellipsis are rejected.
4. If the quote is not in the claimed segment but is in an adjacent turn of
   the same expert (the model was off by one turn), the citation is moved to
   the segment that actually contains it and marked ``corrected``.
5. Re-slices the quote out of the *original* transcript text. What the UI
   shows is the transcript's own characters, not the model's rendering.

Every failed claim is logged at WARNING level and returned in the result, so
failures are visible in tests and in the UI's debug panel rather than being
silently dropped.
"""

from __future__ import annotations

import logging
import unicodedata
from dataclasses import asdict, dataclass

from .parser import Segment, Transcript

log = logging.getLogger("core.verify")

MIN_QUOTE_WORDS = 3
NEIGHBOUR_TURNS = 1  # how many expert turns either side count as "near"

_CHAR_FOLD = {
    "‘": "'", "’": "'", "“": '"', "”": '"',
    "–": "-", "—": "-", " ": " ",
}


def normalize_with_map(text: str) -> tuple[str, list[int]]:
    """Case-fold and reduce every run of whitespace/punctuation to one space.

    Returns the normalised string and, for each of its characters, the index
    of the original character it came from (used to re-slice the original).
    """
    out: list[str] = []
    idx: list[int] = []
    for i, ch in enumerate(text):
        ch = _CHAR_FOLD.get(ch, ch)
        ch = unicodedata.normalize("NFKC", ch)
        if ch.isalnum():
            for c in ch.casefold():
                out.append(c)
                idx.append(i)
        elif out and out[-1] != " ":
            out.append(" ")
            idx.append(i)
    while out and out[-1] == " ":
        out.pop()
        idx.pop()
    return "".join(out), idx


def normalize(text: str) -> str:
    return normalize_with_map(text)[0]


def find_in_segment(quote: str, segment: Segment) -> str | None:
    """Return the exact original substring of ``segment.text`` that matches
    ``quote`` under normalisation, or None."""
    nq = normalize(quote)
    if not nq:
        return None
    ns, idx = normalize_with_map(segment.text)
    # Match on word boundaries so "cost" cannot match inside "costly".
    padded = f" {ns} "
    pos = padded.find(f" {nq} ")
    if pos < 0:
        return None
    start, end = pos, pos + len(nq) - 1  # indices into ns
    original = segment.text[idx[start] : idx[end] + 1]
    return original


@dataclass(frozen=True)
class VerifiedCitation:
    segment_id: str
    expert_id: str
    expert_name: str
    timestamp: str
    quote: str              # exact characters from the transcript
    segment_text: str       # the full turn, for context in the UI
    status: str             # "exact" or "corrected"
    claimed_segment_id: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class FailedCitation:
    claimed_segment_id: str
    quote: str
    reason: str
    context: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


class CitationVerifier:
    def __init__(self, transcripts: list[Transcript]):
        self.transcripts = {t.expert_id: t for t in transcripts}
        self.segments = {s.segment_id: s for t in transcripts for s in t.segments}

    def _neighbours(self, seg: Segment) -> list[Segment]:
        experts = self.transcripts[seg.expert_id].expert_segments
        pos = next(i for i, s in enumerate(experts) if s.segment_id == seg.segment_id)
        lo, hi = max(0, pos - NEIGHBOUR_TURNS), pos + NEIGHBOUR_TURNS + 1
        return [s for s in experts[lo:hi] if s.segment_id != seg.segment_id]

    def verify(
        self,
        segment_id: str,
        quote: str,
        allowed_expert_ids: set[str] | None = None,
        context: str = "",
    ) -> VerifiedCitation | FailedCitation:
        def fail(reason: str) -> FailedCitation:
            f = FailedCitation(segment_id, quote, reason, context)
            log.warning("citation rejected [%s] %s | quote=%r", segment_id, reason, quote)
            return f

        quote = (quote or "").strip()
        if not quote:
            return fail("empty quote")
        if "..." in quote or "…" in quote:
            return fail("quote contains an ellipsis (spliced or truncated quote)")
        if len(normalize(quote).split()) < MIN_QUOTE_WORDS:
            return fail(f"quote shorter than {MIN_QUOTE_WORDS} words")
        seg = self.segments.get(segment_id)
        if seg is None:
            return fail("unknown segment id")
        if not seg.is_expert:
            return fail("segment is an interviewer turn, not expert testimony")
        if allowed_expert_ids and seg.expert_id not in allowed_expert_ids:
            return fail(
                f"segment belongs to {seg.expert_id}, expected one of {sorted(allowed_expert_ids)}"
            )

        exact = find_in_segment(quote, seg)
        if exact is not None:
            return VerifiedCitation(
                seg.segment_id, seg.expert_id, seg.expert_name, seg.timestamp,
                exact, seg.text, "exact", segment_id,
            )
        for n in self._neighbours(seg):
            exact = find_in_segment(quote, n)
            if exact is not None:
                log.warning(
                    "citation corrected: quote claimed at %s found at adjacent turn %s",
                    segment_id, n.segment_id,
                )
                return VerifiedCitation(
                    n.segment_id, n.expert_id, n.expert_name, n.timestamp,
                    exact, n.text, "corrected", segment_id,
                )
        return fail("quote not found verbatim in the claimed segment or adjacent turns")


def verify_payload(
    payload,
    verifier: CitationVerifier,
    allowed_expert_ids: set[str] | None = None,
    _path: str = "$",
) -> tuple[object, list[FailedCitation]]:
    """Walk a model JSON payload and verify every ``citations`` list in place.

    Any dict with a ``citations`` key has each claim ``{segment_id, quote}``
    replaced by a verified citation dict, or removed and reported as a
    failure. If that dict also carries an ``expert_id`` (e.g. one side of a
    disagreement), its citations must come from that expert.
    """
    failures: list[FailedCitation] = []
    if isinstance(payload, dict):
        out = {}
        for key, value in payload.items():
            if key == "citations" and isinstance(value, list):
                scope = allowed_expert_ids
                if payload.get("expert_id"):
                    scope = {payload["expert_id"]}
                verified = []
                seen = set()
                for claim in value:
                    res = verifier.verify(
                        str(claim.get("segment_id", "")),
                        str(claim.get("quote", "")),
                        scope,
                        context=_path,
                    )
                    if isinstance(res, VerifiedCitation):
                        k = (res.segment_id, res.quote)
                        if k not in seen:
                            seen.add(k)
                            verified.append(res.to_dict())
                    else:
                        failures.append(res)
                out[key] = verified
            else:
                out[key], sub = verify_payload(value, verifier, allowed_expert_ids, f"{_path}.{key}")
                failures.extend(sub)
        return out, failures
    if isinstance(payload, list):
        items = []
        for i, item in enumerate(payload):
            v, sub = verify_payload(item, verifier, allowed_expert_ids, f"{_path}[{i}]")
            items.append(v)
            failures.extend(sub)
        return items, failures
    return payload, failures
